package mx.gob.economia.regprov

import mx.gob.economia.regprov.exception.AppException
import mx.gob.economia.regprov.exception.ErrorInfo

import grails.converters.JSON

/**
* Generated by the Shiro plugin. This filters class protects all URLs
* via access control by convention.
*/
class SecurityFilters {
  def filters = {
    all(uri: "/api/**") {
      before = {
        // Ignore direct views (e.g. the default main index page).
        response.setHeader("Cache-Control", "no-cache, must-revalidate")
        if(controllerName == "apiAuth") return true
        try {
          def headerToken = request.getHeader("X-XSRF-TOKEN")
          if(headerToken == null) {
            throw new AppException(ErrorInfo.XSRF_ERROR, "El request no contiene un token de XSRF")
          }
          def subject = SecurityUtils.subject
          if(!subject.isAuthenticated()) {
            throw new AppException(ErrorInfo.SESSION_ERROR, "El usuario no está firmado en la aplicación")
          }
          def sessionToken = subject.session.getAttribute("XSRF_TOKEN")
          if(sessionToken == null) {
            subject.logout()
            throw new AppException(ErrorInfo.SESSION_ERROR, "No hay un token de XSRF en la sesión")
          }
          if(headerToken != sessionToken) {
            subject.logout()
            throw new AppException(ErrorInfo.XSRF_ATTACK_ERROR, "El token de xsrf no corresponde a la sesión")
          }
          return true
        } catch(AppException ex) {
          def info = ex.errorInfo
          def exceptionData = [
          errorId: info.errorId,
          description: info.description,
          severity: info.severity,
          origin: info.origin,
          message: ex.message
          ]
          response.status = 401
          response.contentType = "application/json"
          render exceptionData as JSON
          return false
        }
      }
    }
    all(uri: "/**") {
      before = {
        // Ignore direct views (e.g. the default main index page).
        if (!controllerName) return true
        if(controllerName == "apiAuth") return true

        // Access control by convention.
        accessControl()
      }
    }
  }
}
